# Используем официальный образ Node.js
FROM node:14

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
# COPY warehouse-frontend/package*.json ./
COPY warehouse-frontend/package*.json ./

# Устанавливаем зависимости
RUN npm install --legacy-peer-deps 

# Копируем весь проект в контейнер
# COPY warehouse-frontend/ .
COPY warehouse-frontend .  

# Собираем проект
RUN npm run build

# Команда для запуска сервера разработки
CMD ["npm", "start"]