# Generated by Django 5.1.5 on 2025-02-07 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiplist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shiplist',
            name='unique_id_ship',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
