# Generated by Django 5.1.5 on 2025-02-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveadd',
            name='counterparty',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='archiveadd',
            name='progress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='archiveadd',
            name='warehouse',
            field=models.CharField(default='', max_length=255),
        ),
    ]
