# Generated by Django 5.1.5 on 2025-02-19 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_archiveadd_counterparty_archiveadd_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveNumber', models.CharField(max_length=255)),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('add_date', models.DateField()),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('goods_status', models.CharField(max_length=100)),
                ('newPlace', models.CharField(max_length=100)),
            ],
        ),
    ]
