# Generated by Django 5.1.5 on 2025-02-07 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_shiplist_id_alter_shiplist_unique_id_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addlist',
            name='unique_id_add',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
