# Generated by Django 5.1.5 on 2025-02-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_movelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddata',
            name='add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='addlist',
            name='add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archiveadd',
            name='add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archiveadd',
            name='close_add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archiveproduct',
            name='add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archiveproduct',
            name='close_product_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archiveship',
            name='final_ship_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archiveship',
            name='reserve_data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archiveship',
            name='ship_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='movelist',
            name='add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='placeproduct',
            name='add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservlist',
            name='add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservlist',
            name='reserve_data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservlist',
            name='ship_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shipdata',
            name='ship_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shiplist',
            name='ship_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tranzitdata',
            name='tranz_date',
            field=models.DateTimeField(),
        ),
    ]
