# Generated by Django 5.1.5 on 2025-02-07 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_addlist_id_alter_addlist_unique_id_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservlist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservlist',
            name='unique_id_ship',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
