# Generated by Django 5.1.5 on 2025-02-07 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_reservlist_id_alter_reservlist_unique_id_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeproduct',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='placeproduct',
            name='unique_id_add',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
